#+title: Guide Template

#+PROPERTY: header-args :session none

* Installation
* The Mediator Environment

The Mediator is a variant of ProxySpace that uses a custom dispatch method for replacing the values of its environment variables.  It introduces custom behaviors for replacing synths and patterns, so that storing a synth or pattern in an environment variable automatically stops the previously running synth or pattern.

Examples:

* Patterns and Synths in Mediator Envionment
* EventStream

The EventStream class is an alternative to Pbind.  It is named EventStream because it is a Stream that produces Events.  It replaces the Event producing Routine (formally referred to as Event Stream) that is produced by Pbind.  This is because a Routine does not allow access to its closure variables, and therefore does not permit changing parts of the stream.

#+begin_src sclang
\default +> \test;
#+end_src

* Operators
** **>
Function **> player, envir

Use function to obtain durations and schedule the function with player and envir as arguments.

** @

** @@>
** @>
** &>

<key> &>.<envir> value :

Put value in key <key> of envir <envir>.
Example:

#+begin_src sclang
\freq &>.test 600
#+end_src

#+RESULTS:
: nil

Put value 600 in key \freq of Mediator \test

#+begin_src sclang :session none
1 + 1;
#+end_src

#+RESULTS:
: 2


#+begin_src sclang
1 + 1;
#+end_src

#+RESULTS:
: 2

** !!!
** !!>
** !!*
** !+>
** >>@
** >>!
** >>>
** >>?
** <@
** <!
** <<<
** <+
** <+@
** <?>
** --
** +@>
** +>
** +>!
** +>>
** +><@>
** ++>
** +++
** *>

* OSC
* OSCGroups
* Busses
* Buffers
* Sensors
* Scripts and Scores
* OSC Data Recording
* Presets
* GUI Interfaces
