JointNames.osc(\hip);
JointNames.osc(\hi);
JointNames.osc(\hix);
JointNames.osc(\hiX);
JointNames.osc(\rightLeg);
JointNames.osc(\rl);
JointNames.osc(\rlx);
JointNames.osc(\rlX);
//:bus ...
JointNames.bus(\hip);
JointNames.bus(\hi);
JointNames.bus(\hix);
JointNames.bus(\hiX);
JointNames.bus(\hiy);
JointNames.bus(\hiz);
JointNames.bus(\hiX);
JointNames.bus(\hiY);
JointNames.bus(\hiZ);

JointNames.bus(\rightLeg);
JointNames.bus(\rl);
JointNames.bus(\rlx);
JointNames.bus(\rly);
JointNames.bus(\rlz);
JointNames.bus(\rlX);
//