//: 土 14  6 2025 17:16
r = RokokoData2(\test);
r.sendPort = 22245;
r.addSendOscGroups;
r.loopSegment;
//: 土 14  6 2025 17:16
r = RokokoData2(\giorgos_dog_sequence);
r.sendPort = 22245;
r.load;
r.paths;
r.sendPort = 22245;
r.addSendOscGroups;
r.loopSegment;
//: 土 14  6 2025 17:16
r = RokokoData2(\giorgos_250414_003407);
r.sendPort = 22245;
r.load;
r.paths;
r.sendPort = 22245;
r.addSendOscGroups;
r.loopSegment;
//: 土 14  6 2025 17:16
r = RokokoData2(\giorgos_250414_003228);
r.sendPort = 22245;
r.load;
r.paths;
r.sendPort = 22245;
r.addSendOscGroups;
r.loopSegment;
//: 土 14  6 2025 17:16
r = RokokoData2(\giorgos_250414_003102);
r.sendPort = 22245;
r.load;
r.paths;
r.sendPort = 22245;
r.addSendOscGroups;
r.loopSegment;
//: 土 14  6 2025 17:16
r = RokokoData2(\giorgos_250414_002557);
r.sendPort = 22245;
r.load;
r.paths;
r.sendPort = 22245;
r.addSendOscGroups;
r.loopSegment;
//: 土 14  6 2025 17:16
r = RokokoData2(\giorgos_250414_001919);
r.sendPort = 22245;
r.load;
r.paths;
r.sendPort = 22245;
r.addSendOscGroups;
r.loopSegment;
//: