// Exporting 16 snippets on 230830_105049
//:--[10034.533281]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]
//:--[10034.534107375]
[ '/code', "'yoshimitsu'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 26035430, 'buf': 'weddell', 'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainecho', 'trate': [ 0.48412698412698, \"\\\\z5.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x5.sr\", 'on' ] )" ]
//:--[10034.537421166]
[ '/code', "{Xyz(5, 0.2, 0.1, 1.5)}@>.yoshimitsu \\amp" ]
//:--[10034.539512]
[ '/code', "{\\x5.sr}@>.yoshimitsu \\pos" ]
//:--[10034.540211333]
[ '/code', "{\\z5.sr}@>.yoshimitsu \\trate" ]
//:--[10034.567970333]
[ '/code', '\yoshimitsu.envir.stopSynths' ]
//:--[10040.952152791]
[ '/code', "\\jun.envir.stopSynths" ]
//:--[10040.953089333]
[ '/code', "'jun'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 1798102, 'buf': 'noisebirdsclick', 'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainecho', 'trate': [ 0.48412698412698, \"\\\\z5.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x5.sr\", 'on' ] )" ]
//:--[10040.958790583]
[ '/code', "{Xyz(5, 0.2, 0.1, 1.5)}@>.jun \\amp" ]
//:--[10040.960769458]
[ '/code', "{\\x5.sr}@>.jun \\pos" ]
//:--[10040.961873]
[ '/code', "{\\z5.sr}@>.jun \\trate" ]
//:--[10080.656511916]
[ '/code', '\yoshimitsu.envir.stopSynths' ]
//:--[10080.658829791]
[ '/code', '\'yoshimitsu\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 26035430, \'buf\': \'weddell\', \'amp\': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainfroth\', \'trate\': [ 0.48412698412698, "\\z1.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x1.sr", \'on\' ] )' ]
//:--[10080.666735583]
[ '/code', '{Xyz(1, 0.2, 0.1, 1.5)}@>.yoshimitsu \amp' ]
//:--[10080.667485125]
[ '/code', '{\x1.sr}@>.yoshimitsu \pos' ]
//:--[10080.672107166]
[ '/code', '{\z1.sr}@>.yoshimitsu \trate' ]

//the end

