// Exporting 6 snippets on 230907_203021
//:--[16677.324732708]
[ '/code', '\mary.envir.stopSynths' ]
//:--[16677.326130083]
[ '/code', '\'mary\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 398624, \'buf\': \'hanbaiki\', \'amp\': [ 1.0, "(Xyz(5, 0.2, 0.1, 1.5)+Xyz(7, 0.2, 0.1, 1.5))/3", \'on\' ], 
  \'startframe\': 0, \'rate\': [ 1, "\\z7.sr", \'on\' ], \'playfunc\': \'grainecho\', \'trate\': [ 0.48412698412698, "\\z5.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x5.sr", \'on\' ] )' ]
//:--[16677.340080083]
[ '/code', '{(Xyz(5, 0.2, 0.1, 1.5)+Xyz(7, 0.2, 0.1, 1.5))/3}@>.mary \amp' ]
//:--[16677.423223083]
[ '/code', '{\z5.sr}@>.mary \trate' ]
//:--[16677.425091958]
[ '/code', '{\z7.sr}@>.mary \rate' ]
//:--[16819.235822458]
[ '/code', '\mary.envir.stopSynths' ]

//the end

