// Exporting 8 snippets on 230830_104916
//:--[6309.323017916]
[ '/code', '{\x5.sr}@>.mary \pos' ]
//:--[6310.265820125]
[ '/code', '{\z5.sr}@>.mary \trate' ]
//:--[6408.169999708]
[ '/code', '\mary.envir.stopSynths' ]
//:--[6408.176142833]
[ '/code', '\'mary\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 2451380, \'buf\': \'bird_crickets\', \'amp\': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainfroth\', \'trate\': [ 0.48412698412698, "\\z5.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x5.sr", \'on\' ] )' ]
//:--[6408.207036583]
[ '/code', '{Xyz(5, 0.2, 0.1, 1.5)}@>.mary \amp' ]
//:--[6408.229530875]
[ '/code', '{\x5.sr}@>.mary \pos' ]
//:--[6408.230838833]
[ '/code', '{\z5.sr}@>.mary \trate' ]
//:--[6455.089403458]
[ '/code', '\mary.envir.stopSynths' ]

//the end

