// Exporting 5 snippets on 230830_223628
//:--[16526.242494125]
[ '/code', '\mary.envir.stopSynths' ]
//:--[16526.243772541]
[ '/code', '\'mary\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 398624, \'buf\': \'hanbaiki\', \'amp\': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainecho\', \'trate\': [ 0.48412698412698, "\\z5.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x5.sr", \'on\' ] )' ]
//:--[16526.256408958]
[ '/code', '{Xyz(5, 0.2, 0.1, 1.5)}@>.mary \amp' ]
//:--[16526.256538625]
[ '/code', '{\x5.sr}@>.mary \pos' ]
//:--[16526.259076541]
[ '/code', '{\z5.sr}@>.mary \trate' ]

//the end

