// Exporting 12 snippets on 230907_205644
//:--[15183.684933791]
[ '/code', '\mary.envir.stopSynths' ]
//:--[15183.685173416]
[ '/code', '\'mary\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 1798102, \'buf\': \'noisebirdsclick\', \'amp\': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainfroth\', \'trate\': [ 0.48412698412698, "\\z5.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x5.sr", \'on\' ] )' ]
//:--[15183.700586375]
[ '/code', '{Xyz(5, 0.2, 0.1, 1.5)}@>.mary \amp' ]
//:--[15183.705742916]
[ '/code', '{\x5.sr}@>.mary \pos' ]
//:--[15183.712773791]
[ '/code', '{\z5.sr}@>.mary \trate' ]
//:--[15187.63783675]
[ '/code', '\sanya.envir.stopSynths' ]
//:--[15187.639775416]
[ '/code', '\'sanya\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 1862334, \'buf\': \'crickets\', \'amp\': [ 1.0, "Xyz(7, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainfroth\', \'trate\': [ 0.48412698412698, "\\z7.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x7.sr", \'on\' ] )' ]
//:--[15187.664973]
[ '/code', '{Xyz(7, 0.2, 0.1, 1.5)}@>.sanya \amp' ]
//:--[15187.668903708]
[ '/code', '{\x7.sr}@>.sanya \pos' ]
//:--[15187.671392416]
[ '/code', '{\z7.sr}@>.sanya \trate' ]
//:--[15411.005293791]
[ '/code', '\mary.envir.stopSynths' ]
//:--[15461.241495708]
[ '/code', '\sanya.envir.stopSynths' ]

//the end

