// Exporting 16 snippets on 230830_105124
//:--[11414.904019166]
[ '/code', "\\jun.envir.stopSynths" ]
//:--[11414.9069405]
[ '/code', "'jun'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 27691528, 'buf': 'swallows', 'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.48412698412698, \"\\\\z5.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x5.sr\", 'on' ] )" ]
//:--[11414.910870083]
[ '/code', "{Xyz(5, 0.2, 0.1, 1.5)}@>.jun \\amp" ]
//:--[11414.912904125]
[ '/code', "{\\x5.sr}@>.jun \\pos" ]
//:--[11414.913745125]
[ '/code', "{\\z5.sr}@>.jun \\trate" ]
//:--[11419.034711875]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]
//:--[11419.035647333]
[ '/code', "'yoshimitsu'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 640128, 'buf': 'weddellpock', 'amp': [ 1.0, \"Xyz(1, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.48412698412698, \"\\\\z1.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x1.sr\", 'on' ] )" ]
//:--[11419.040085833]
[ '/code', "{Xyz(1, 0.2, 0.1, 1.5)}@>.yoshimitsu \\amp" ]
//:--[11419.041564875]
[ '/code', "{\\x1.sr}@>.yoshimitsu \\pos" ]
//:--[11419.042103458]
[ '/code', "{\\z1.sr}@>.yoshimitsu \\trate" ]
//:--[11608.867004708]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]
//:--[11610.198568291]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]
//:--[11610.201605708]
[ '/code', "'yoshimitsu'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 26035430, 'buf': 'weddell', 'amp': [ 1.0, \"Xyz(1, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.48412698412698, \"\\\\z1.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x1.sr\", 'on' ] )" ]
//:--[11610.206947208]
[ '/code', "{Xyz(1, 0.2, 0.1, 1.5)}@>.yoshimitsu \\amp" ]
//:--[11610.208210291]
[ '/code', "{\\x1.sr}@>.yoshimitsu \\pos" ]
//:--[11610.208824708]
[ '/code', "{\\z1.sr}@>.yoshimitsu \\trate" ]

//the end

