// Exporting 12 snippets on 230830_105220
//:--[13032.417078]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]
//:--[13032.418034375]
[ '/code', "'yoshimitsu'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 772138, 'buf': 'rough_steps', 'amp': [ 1.0, \"Xyz(1, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.48412698412698, \"\\\\z1.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x1.sr\", 'on' ] )" ]
//:--[13032.421986041]
[ '/code', "{Xyz(1, 0.2, 0.1, 1.5)}@>.yoshimitsu \\amp" ]
//:--[13032.423872875]
[ '/code', "{\\x1.sr}@>.yoshimitsu \\pos" ]
//:--[13032.424658416]
[ '/code', "{\\z1.sr}@>.yoshimitsu \\trate" ]
//:--[13034.715898791]
[ '/code', "\\mary.envir.stopSynths" ]
//:--[13034.716768833]
[ '/code', "'mary'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 2451380, 'buf': 'bird_crickets', 'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.48412698412698, \"\\\\z5.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x5.sr\", 'on' ] )" ]
//:--[13034.721453125]
[ '/code', "{Xyz(5, 0.2, 0.1, 1.5)}@>.mary \\amp" ]
//:--[13034.722722166]
[ '/code', "{\\x5.sr}@>.mary \\pos" ]
//:--[13034.723263625]
[ '/code', "{\\z5.sr}@>.mary \\trate" ]
//:--[13228.845777333]
[ '/code', "\\mary.envir.stopSynths" ]
//:--[13231.78292675]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]

//the end

