// Exporting 15 snippets on 230830_105108
//:--[10726.195781458]
[ '/code', "\\jun.envir.stopSynths" ]
//:--[10726.198800625]
[ '/code', "'jun'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 27691528, 'buf': 'swallows', 'dur': [ 0.0, \"\", 'off' ], 
  'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'on' ], 'startframe': 0, 'playfunc': 'grainecho', 'trate': [ 0.48412698412698, \"\\\\z5.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x5.sr\", 'on' ] )" ]
//:--[10726.202684375]
[ '/code', "{Xyz(5, 0.2, 0.1, 1.5)}@>.jun \\amp" ]
//:--[10726.204840541]
[ '/code', "{\\x5.sr}@>.jun \\pos" ]
//:--[10726.205761083]
[ '/code', "{\\z5.sr}@>.jun \\trate" ]
//:--[10735.210553458]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]
//:--[10735.211475291]
[ '/code', "'yoshimitsu'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 5445632, 'buf': 'yang_bird', 'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainecho', 'trate': [ 0.48412698412698, \"\\\\z5.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x5.sr\", 'on' ] )" ]
//:--[10735.217814291]
[ '/code', "{Xyz(5, 0.2, 0.1, 1.5)}@>.yoshimitsu \\amp" ]
//:--[10735.219956625]
[ '/code', "{\\x5.sr}@>.yoshimitsu \\pos" ]
//:--[10735.220703958]
[ '/code', "{\\z5.sr}@>.yoshimitsu \\trate" ]
//:--[10778.418716166]
[ '/code', '\yoshimitsu.envir.stopSynths' ]
//:--[10778.419023791]
[ '/code', '\'yoshimitsu\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 5445632, \'buf\': \'yang_bird\', \'amp\': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainfroth\', \'trate\': [ 0.48412698412698, "\\z1.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x1.sr", \'on\' ] )' ]
//:--[10778.427714166]
[ '/code', '{Xyz(1, 0.2, 0.1, 1.5)}@>.yoshimitsu \amp' ]
//:--[10778.4297995]
[ '/code', '{\x1.sr}@>.yoshimitsu \pos' ]
//:--[10778.430599458]
[ '/code', '{\z1.sr}@>.yoshimitsu \trate' ]

//the end

