// Exporting 12 snippets on 230907_205615
//:--[14532.285155375]
[ '/code', '\sanya.envir.stopSynths' ]
//:--[14532.287135125]
[ '/code', '\'sanya\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 135274, \'buf\': \'fones\', \'amp\': [ 1.0, "Xyz(7, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainfroth\', \'trate\': [ 0.48412698412698, "\\z7.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x7.sr", \'on\' ] )' ]
//:--[14532.348438625]
[ '/code', '{Xyz(7, 0.2, 0.1, 1.5)}@>.sanya \amp' ]
//:--[14532.348766208]
[ '/code', '{\x7.sr}@>.sanya \pos' ]
//:--[14532.371304]
[ '/code', '{\z7.sr}@>.sanya \trate' ]
//:--[14543.433697458]
[ '/code', '\mary.envir.stopSynths' ]
//:--[14543.43865475]
[ '/code', '\'mary\'.envir play: ( \'vol\': [ 3.356638951877, "", \'off\' ], \'endframe\': 27691528, \'buf\': \'swallows\', \'amp\': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", \'on\' ], 
  \'startframe\': 0, \'playfunc\': \'grainfroth\', \'trate\': [ 0.48412698412698, "\\z5.sr", \'on\' ], \'pos\': [ 0.079365079365079, "\\x5.sr", \'on\' ] )' ]
//:--[14543.45601475]
[ '/code', '{Xyz(5, 0.2, 0.1, 1.5)}@>.mary \amp' ]
//:--[14543.466550708]
[ '/code', '{\x5.sr}@>.mary \pos' ]
//:--[14543.4682155]
[ '/code', '{\z5.sr}@>.mary \trate' ]
//:--[14762.988030291]
[ '/code', '\mary.envir.stopSynths' ]
//:--[14766.691389583]
[ '/code', '\sanya.envir.stopSynths' ]

//the end

