#+title: Help For Help

* COMMENT Header
# The header should export the following items in schelp format:
# CLASS::MediatorGui
# categories::sc-hacks-redux>gui
# summary:: Create a window all current Mediators in a ListView, and the keys of the Mediator currently selected in that ListView.
# see also: Mediator

Create a window for viewing the contents of a Mediators' environment.

See also: Mediator class.

Note: This file was edited to test export.

# Export settings such as file name usw.
* Exporting the header of the file:

Create a subtree modeled after the subtree below.
The subtree must contain the following properties, which export the header of the schelp file:

The following line generates the Categories line in the schelp file:
:EXPORT_KEYWORDS: Libraries>scHacks

The following line says which sections will be exported.  Sections that have the tag =classHELP= will be exported
:EXPORT_SELECT_TAGS: classHELP

This property sets the directory where the schelp file will be exported.
:o2m_EXPORT_DIR: (catdir (prop "prop_dir") "HelpSource" "Classes")
the property (prop "prop_dir") is defined in the header of the file to export, as follows:
#+PROPERTY: prop_dir "../../"

:EXPORT_TITLE: MediatorGui
This generates a header line
TITLE:: MediatorGui
at the beginning of the file.
This should be the class name.

:EXPORT_FILE_NAME: MediatorGui
This is the main body of the file name to be generated for exporting.  SO the file will be here:
"MediatorGui.schelp"

:EXPORT_KEYWORDS: Libraries>scHacks
This generates a line like this:
categories:: Libraries>scHacks

:EXPORT_RELATED: Classes/Mediator
This generates:
related:: Classes/Mediator

:ID:       20250305T115430.380763
System generated. The user does not need to write this line.

* o2m exports
:PROPERTIES:
:EXPORT_OPTIONS: d:nil
:END:
** o2m SC-help exports
:PROPERTIES:
:o2m_SETUPFILE: (ox-sc-setupfile)
:o2m_SELECT_BACKENDS: SC-help
:END:
*** Mediator class help :o2m:
:PROPERTIES:
:o2m_EXPORT_DIR: (catdir (prop "prop_dir") "HelpSource" "Classes")
:EXPORT_TITLE: MediatorGui
:EXPORT_FILE_NAME: MediatorGui
:EXPORT_SELECT_TAGS: classHELP
:EXPORT_KEYWORDS: Libraries>scHacks
:EXPORT_RELATED: Classes/Mediator
:EXPORT_SUMMARY: Create a window for viewing the contents of a Mediators' environment.
:ID:       20250305T115430.380763
:END:

[[elisp:(find-file (expand-file-name (cdf (prop "prop_dir") "HelpSource" "Classes" "MediatorGui.schelp")))][MediatorGui.schelp]]

[[scHELP:Reference/SCDocSyntax][scHelp(byHand) for Reference/SCDocSyntax]]

#+begin_src sclang :results silent
  SCDoc.indexAllDocuments
#+end_src

* Description :classHELP:sc_description:
# This generates a description:: schelp header and exports the text contained in the present subtree underneath.
This class does not have any subclasses. It a draft for developing a more functional Gui for Mediators.
* Class methods of MediatorGui -- heading contents is ignored :classHELP:sc_classmethods:
# This section should be in schelp section CASSMETHODS:: Like this:
# CLASSMETHODS::

** COMMENT new(mediator)
# The schelp code required here is:
# method::new
# Create a MediatorGui window for mediator named by the argument. If such a window already exists, bring it to the front.
# argument::symbol
# The name of the mediator to display in the GUI.

Create a MediatorGui window for the mediator named by the argument. If such a window already exists, bring it to the front. The argument =mediator= must be a symbol.
** new       :classHELP:sc_METHOD:
*** mediator                                                                             :sc_argument:
Create a MediatorGui window for the mediator named by the argument. If such a window already exists, bring it to the front. The argument =mediator= must be a symbol.

* Instance methods -- heading contents is ignored :classHELP:sc_instancemethods:
# Code required here is:
# INSTANCEMETHODS::

** init                                                                                     :sc_method:
Internal method. Add self as mediator to dependent.  Enable updates when the mediator changes.

** COMMENT update(mediator, key, value)
** update                                                                                   :sc_method:
This method is called when the mediator changes. It calls =\changed= on the MediatorGui.  In response to this, the GUI window, if it is open, updates its contents.
*** mediator                                                                             :sc_argument:
the mediator that changed
*** keys                                                                                 :sc_argument:
Symbol. The key that changed
*** value                                                                                :sc_argument:
The value that changed.

* Available tags:

#+tags: classHELP(C) refHELP(R) guideHELP(G) tutorHELP(T) overHELP(O) otherHELP(o)
#+tags: { sc_section(s) sc_subsection(b) sc_description(D) sc_classmethods(c) sc_instancemethods(i) sc_copymethod(y) sc_METHOD(M) sc_method(m) sc_private(p) sc_examples(e) sc_argument(a) sc_returns(r) sc_discussion(d) }
