// 月 21  4 2025 11:38
// Test pushing environments:
// =========== 1
// From the default current environment of local user,
// push a new environment in the local user
// =========== 2
// From the default current environment of the local user,
// get and push the default environment of another user
// =========== 3
// From the default current environment of the local user,
// get and bush an arbitrary environment of another user
// - from default current environment of user
// =========== 4
// From an arbitrary environment of an arbitrary user,
// - switch back to the home environment of the local user
// =========== 5
// From an arbitrary environment of an arbitrary user,
// - switch to an arbitrary environment of the local user