/*presets for jun saved at 230823_174348*/

//: (0) jun
"TriggerFuncs_Experimental_Jun"
//: (1) jun
"01_trigger_step_test_score"
//: (2) jun
"00_FromSineCrossingIntro230821_160835"
//: (3) jun grainmagshift hanbaiki
//Comments...
//...
(
'amp': [ 1, "", 'off' ],
'buf': 'hanbaiki',
'endframe': [ 289880, nil, nil ],
'playfunc': 'grainmagshift',
'pos': [ 0.12301587301587, "", 'off' ],
'rate': [ 1, "", 'off' ],
'shift': [ -200.0, "", 'off' ],
'startframe': [ 2726, nil, nil ],
'stretch': [ 0.60464285714286, "", 'off' ],
'trate': [ 50, "" ],
'vol': [ 6.6824137062232, "", 'off' ],
)
/* THE END */