#+TITLE: 23100 2sakurako Show Concept 231002

* Japanese Original
ギリシャプロジェクト 提案書
テーマ: 水
BC600年頃 ギリシャの哲学者タレスが言った言葉「万物の根源は水である」
ここから「水」を通してギリシャ、中国、そして日本を"繋げていく"
①日本と中国の水の神様
・龍/河伯(中国)
雨や洪水を呼び込む生きもの
・天水分神 アマノミクマリノカミ(日本)
古事記に登場する水の分配を司る神
⇒パフォーマー4人共にこれら神様の象徴的なパフォーマンスをおこなう
②水の神様から私たちの社会・労働に繋がる
・龍と天水分神は民間に密接している
→防災や農耕
③水は"繋ぐ"の象徴
今回の企画の主軸"ギリシャと日本を繋ぐ"に基づき、エレウシスの神を日本に運んでくる。"オンライン"という虚構のものと"神様"という目に見えないモノを共通点として繋ぐ。
まとめると…
中国と日本の水の神様の表現により、水は私たちの生活に欠かせないものであることをパフォーマンスで表現
そしてその神様たちがエレウシスをオンラインで繋げて日本に運んでくる
具体的なパフォーマンス内容
場所:橋や川のそば？(場所によって地域の労働者たちの存在を象徴できたらいいかも？ 例えば遠くからスカイツリーが見えるところとか)
蔵前橋↓


首都高に覆われた日本橋↓

浅草橋駅 高架下↓

かっぱ橋道具街↓

内容:
①水の象徴的な動き
例)一定の方向に動く、止まらない、動くというより動かされる
     荒い動き(龍)と水をもたらす清らかな動き(天水分神)
②エレウシスと繋がり、運んでくる
例)ギリシャのパフォーマーと動きが徐々に重なる
両国のパフォーマーの動きが大きくなってから徐々に静まり、エレウシスの神が来たことを全員の目線により知らせる
または、センサーの表現で知らせる


* Tranlation by Deepl

Greece Project Proposal
Topic: Water
Around 600 BC, the Greek philosopher Thales said, "The root of all things is water.
From here, we will "connect" Greece, China, and Japan through "water".
Water Gods of Japan and China
Dragon/He Bo (China)
Creature that brings rain and floods
Ama-no-mikumari-no-kami (Japan)
Amanomikumari-no-kami (Japan) A god who controls the distribution of water in the Kojiki (Records of Ancient Matters)
⇒The four performers will give a symbolic performance of these deities.
The water god is connected to our society and labor.
Dragon and heavenly water divinities are closely connected to the people
→The dragon and the heavenly water divinity are closely connected to the people's society and labor.
Water is a symbol of "connection
Based on the main axis of this project, "Connecting Greece and Japan," we will bring the god of Eleusis to Japan. The fictional "online" and the invisible "god" are connected as a common point.
In summary...
The performance expresses that water is indispensable to our lives through the representation of water gods in China and Japan.
The gods connect Eleusis online and bring it to Japan.
Specific performance details
Location: Near a bridge or a river? (It would be nice if the location could symbolize the presence of local workers? For example, a place where the Sky Tree can be seen from a distance)
Kuramae Bridge


Nihonbashi bridge covered by the Metropolitan Expressway

Asakusabashi station under the elevated railway tracks

Kappabashi tool-gai ↓ Kappabashi station elevated area

Contents: 1.
1) Symbolic movement of water
e.g.) moving in a certain direction, not stopping, being moved rather than moving
     Rough movement (dragon) and pure movement that brings water (Tensui-bunshin)
(2) Connected to Eleusis and brings it in
Example) Movements gradually overlap with Greek performers
Gradual quieting down after the movement of both performers increases, informing by all eyes that the god of Eleusis has arrived
Or informing by the expression of the sensor

* Translation by Chat gpt
