// Exporting 10 snippets on 230830_105203
//:--[12375.49440325]
[ '/code', "\\yoshimitsu.envir.stopSynths" ]
//:--[12375.496544458]
[ '/code', "'yoshimitsu'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 979297, 'buf': 'cricket_ff', 'amp': [ 1.0, \"Xyz(1, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.48412698412698, \"\\\\z1.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x1.sr\", 'on' ] )" ]
//:--[12375.500049083]
[ '/code', "{Xyz(1, 0.2, 0.1, 1.5)}@>.yoshimitsu \\amp" ]
//:--[12375.501658291]
[ '/code', "{\\x1.sr}@>.yoshimitsu \\pos" ]
//:--[12375.502235]
[ '/code', "{\\z1.sr}@>.yoshimitsu \\trate" ]
//:--[12381.128041208]
[ '/code', "\\jun.envir.stopSynths" ]
//:--[12381.129925291]
[ '/code', "'jun'.envir play: ( 'vol': [ 3.356638951877, \"\", 'off' ], 'endframe': 27691528, 'buf': 'swallows', 'amp': [ 1.0, \"Xyz(5, 0.2, 0.1, 1.5)\", 'on' ], 
  'startframe': 0, 'playfunc': 'grainfroth', 'trate': [ 0.48412698412698, \"\\\\z5.sr\", 'on' ], 'pos': [ 0.079365079365079, \"\\\\x5.sr\", 'on' ] )" ]
//:--[12381.133315291]
[ '/code', "{Xyz(5, 0.2, 0.1, 1.5)}@>.jun \\amp" ]
//:--[12381.134647625]
[ '/code', "{\\x5.sr}@>.jun \\pos" ]
//:--[12381.135304583]
[ '/code', "{\\z5.sr}@>.jun \\trate" ]

//the end

