/*presets for dimitra saved at 231022_112741*/

//: (0) dimitra grainfrothl japasea
//scene 1 
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'japasea',
'endframe': 2451380,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z2.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) dimitra grainfrothl sarizaplasticbottle
//scene 2 
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sarizaplasticbottle',
'endframe': 6750651,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) dimitra grainfrothl sarizaplasticbottle2
//scene 3 
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sarizaplasticbottle2',
'endframe': 3105211,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) dimitra grainfrothl sarizasuiryu
//scene 4 
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sarizasuiryu',
'endframe': 107520,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) dimitra grainfrothl shireimarina
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'shireimarina',
'endframe': 979297,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */