/*presets for sanya saved at 230830_195041*/
// LEFT HAND
//: (0) sanya grainfrothl columbia
//scene 1
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'japanbrook',
'endframe': 2451380,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x6.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z6.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) sanya grainfrothl wind_moderate
//scene 2
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'suiryuzemi',
'endframe': 6750651,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x6.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z6.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) sanya grainfrothl yangdrums
//scene 3
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takiike',
'endframe': 3105211,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x6.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z6.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) sanya grainfrothl hanbaiki
//scene 4
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takikoorogi',
'endframe': 107520,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x6.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z6.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) sanya grainfrothl noisebirdsclick
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takisuiryu',
'endframe': 979297,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x6.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z6.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)

//: (4) sanya grainfrothl noisebirdsclick
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takizemi',
'endframe': 979297,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x6.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z6.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
