/*presets for jun saved at 230825_002305*/

//: (0) jun grainfroth bird_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'bird_crickets',
'endframe': 2451380,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) jun grainaround birdcarman
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarman',
'endframe': 6750651,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) jun grainaround birdcarmanshort
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarmanshort',
'endframe': 3105211,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) jun grainaround columbia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'columbia',
'endframe': 107520,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) jun grainaround cricket_ff
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_ff',
'endframe': 979297,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (5) jun grainaround cricket_taps
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_taps',
'endframe': 544543,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (6) jun grainaround crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crickets',
'endframe': 1862334,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (7) jun grainaround crossing
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crossing',
'endframe': 1406259,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (8) jun grainaround default
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'default',
'endframe': 188893,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (9) jun grainaround echo_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'echo_crickets',
'endframe': 2746425,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (10) jun grainaround fones
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'fones',
'endframe': 135274,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (11) jun grainaround hanbaiki
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'hanbaiki',
'endframe': 398624,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (12) jun grainaround kiiroi
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'kiiroi',
'endframe': 473791,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (13) jun grainaround lake_plane
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'lake_plane',
'endframe': 1067182,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (14) jun grainaround loud_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'loud_crickets',
'endframe': 2121727,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (15) jun grainaround melodia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodia',
'endframe': 705600,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (16) jun grainaround melodic_road
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodic_road',
'endframe': 1167623,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (17) jun grainaround noisebirdsclick
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 1798102,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (18) jun grainaround pilgrims
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'pilgrims',
'endframe': 2580480,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (19) jun grainaround rough_steps
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'rough_steps',
'endframe': 772138,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (20) jun grainaround silence
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'silence',
'endframe': 441000,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (21) jun grainaround swallows
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'swallows',
'endframe': 27691528,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (22) jun grainaround sweet_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sweet_crickets',
'endframe': 2746425,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (23) jun grainaround takunia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takunia',
'endframe': 187145,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (24) jun grainaround weddell
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 26035430,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (25) jun grainaround weddellpock
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddellpock',
'endframe': 640128,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (26) jun grainaround wind_moderate
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_moderate',
'endframe': 2147840,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (27) jun grainaround wind_strong
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_strong',
'endframe': 3889920,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (28) jun grainaround yang_bird
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yang_bird',
'endframe': 5445632,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (29) jun grainaround yangdrums
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yangdrums',
'endframe': 10656768,
'playfunc': 'grainaround',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */