/*presets for jun saved at 230824_222229*/

//: (0) jun freeze [ default,  ]
(
'amp': [ 0, "" ],
'buf': [ 'default', "" ],
'endframe': [ 188893, "" ],
'freeze': [ 0, "" ],
'playfunc': 'freeze',
'rate': [ 1, "" ],
'startframe': [ 0, "" ],
'trig': [ 0, "" ],
'vol': [ 1, "" ],
)
//: (1) jun grainloop [ default,  ]
(
'amp': [ 0, "" ],
'buf': [ 'default', "" ],
'endframe': [ 188893, "" ],
'playfunc': 'grainloop',
'startframe': [ 0, "" ],
)
//: (2) jun grainfroth [ default,  ]
(
'amp': [ 0, "" ],
'buf': [ 'default', "" ],
'endframe': [ 188893, "" ],
'playfunc': 'grainfroth',
'pos': [ 0, "" ],
'startframe': [ 0, "" ],
'trate': [ 0, "" ],
'vol': [ 1, "" ],
)
//: (3) jun grainfroth [ default,  ]
(
'amp': [ 0.55656336608718, "", 'off' ],
'buf': [ 'default', "" ],
'endframe': [ 188893, "" ],
'playfunc': 'grainfroth',
'pos': [ 0.54761904761905, "", 'off' ],
'startframe': [ 0, "" ],
'trate': [ 0.48412698412698, "", 'off' ],
'vol': [ 4.5508944318468, "", 'off' ],
)
//: (4) jun grainmagshift hanbaiki
(
'amp': [ 1, "", 'off' ],
'buf': 'hanbaiki',
'endframe': [ 289880, nil, nil ],
'playfunc': 'grainmagshift',
'pos': [ 0.12301587301587, "", 'off' ],
'rate': [ 1, "", 'off' ],
'shift': [ -200.0, "", 'off' ],
'startframe': [ 2726, nil, nil ],
'stretch': [ 0.60464285714286, "", 'off' ],
'trate': [ 50, "" ],
'vol': [ 6.6824137062232, "", 'off' ],
)
/* THE END */