/*presets for jun saved at 230823_134710*/

//: (0) jun grainmagshift hanbaiki
//Here are some comments for this presettttt!   all taken away again.
//ah
(
'amp': [ 1, "", 'off' ],
'buf': 'hanbaiki',
'endframe': [ 289880, nil, nil ],
'playfunc': 'grainmagshift',
'pos': [ 0.12301587301587, "", 'off' ],
'rate': [ 1, "", 'off' ],
'shift': [ -200.0, "", 'off' ],
'startframe': [ 2726, nil, nil ],
'stretch': [ 0.60464285714286, "", 'off' ],
'trate': [ 50, "" ],
'vol': [ 6.6824137062232, "", 'off' ],
)
/* THE END */