/*presets for timevid saved at 231021_172039*/

//: (0) timevid grainfrothl kojohaisuizemi
//scene 3   
(
'amp': [ 1.0, "Xyz(10, 0.2, 0.1, 1.5) + Xyz(11, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'kojohaisuizemi',
'endframe': 3105211,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x10.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z10.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) timevid grainfrothl marinaboto
//scene 4   
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'marinaboto',
'endframe': 979297,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */