/*presets for jun saved at 230825_002305*/

//: (0) jun graintornado bird_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'bird_crickets',
'endframe': 2451380,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) jun graintornado birdcarman
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarman',
'endframe': 6750651,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) jun graintornado birdcarmanshort
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarmanshort',
'endframe': 3105211,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) jun graintornado columbia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'columbia',
'endframe': 107520,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) jun graintornado cricket_ff
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_ff',
'endframe': 979297,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (5) jun graintornado cricket_taps
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_taps',
'endframe': 544543,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (6) jun graintornado crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crickets',
'endframe': 1862334,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (7) jun graintornado crossing
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crossing',
'endframe': 1406259,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (8) jun graintornado default
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'default',
'endframe': 188893,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (9) jun graintornado echo_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'echo_crickets',
'endframe': 2746425,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (10) jun graintornado fones
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'fones',
'endframe': 135274,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (11) jun graintornado hanbaiki
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'hanbaiki',
'endframe': 398624,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (12) jun graintornado kiiroi
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'kiiroi',
'endframe': 473791,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (13) jun graintornado lake_plane
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'lake_plane',
'endframe': 1067182,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (14) jun graintornado loud_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'loud_crickets',
'endframe': 2121727,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (15) jun graintornado melodia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodia',
'endframe': 705600,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (16) jun graintornado melodic_road
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodic_road',
'endframe': 1167623,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (17) jun graintornado noisebirdsclick
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 1798102,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (18) jun graintornado pilgrims
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'pilgrims',
'endframe': 2580480,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (19) jun graintornado rough_steps
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'rough_steps',
'endframe': 772138,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (20) jun graintornado silence
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'silence',
'endframe': 441000,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (21) jun graintornado swallows
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'swallows',
'endframe': 27691528,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (22) jun graintornado sweet_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sweet_crickets',
'endframe': 2746425,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (23) jun graintornado takunia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takunia',
'endframe': 187145,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (24) jun graintornado weddell
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 26035430,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (25) jun graintornado weddellpock
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddellpock',
'endframe': 640128,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (26) jun graintornado wind_moderate
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_moderate',
'endframe': 2147840,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (27) jun graintornado wind_strong
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_strong',
'endframe': 3889920,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (28) jun graintornado yang_bird
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yang_bird',
'endframe': 5445632,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (29) jun graintornado yangdrums
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yangdrums',
'endframe': 10656768,
'playfunc': 'graintornado',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */