/*presets for jun saved at 230825_002305*/

//: (0) jun grain0 bird_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'bird_crickets',
'endframe': 2451380,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) jun grain0 birdcarman
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarman',
'endframe': 6750651,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) jun grain0 birdcarmanshort
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarmanshort',
'endframe': 3105211,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) jun grain0 columbia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'columbia',
'endframe': 107520,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) jun grain0 cricket_ff
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_ff',
'endframe': 979297,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (5) jun grain0 cricket_taps
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_taps',
'endframe': 544543,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (6) jun grain0 crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crickets',
'endframe': 1862334,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (7) jun grain0 crossing
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crossing',
'endframe': 1406259,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (8) jun grain0 default
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'default',
'endframe': 188893,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (9) jun grain0 echo_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'echo_crickets',
'endframe': 2746425,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (10) jun grain0 fones
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'fones',
'endframe': 135274,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (11) jun grain0 hanbaiki
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'hanbaiki',
'endframe': 398624,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (12) jun grain0 kiiroi
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'kiiroi',
'endframe': 473791,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (13) jun grain0 lake_plane
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'lake_plane',
'endframe': 1067182,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (14) jun grain0 loud_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'loud_crickets',
'endframe': 2121727,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (15) jun grain0 melodia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodia',
'endframe': 705600,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (16) jun grain0 melodic_road
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodic_road',
'endframe': 1167623,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (17) jun grain0 noisebirdsclick
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 1798102,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (18) jun grain0 pilgrims
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'pilgrims',
'endframe': 2580480,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (19) jun grain0 rough_steps
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'rough_steps',
'endframe': 772138,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (20) jun grain0 silence
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'silence',
'endframe': 441000,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (21) jun grain0 swallows
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'swallows',
'endframe': 27691528,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (22) jun grain0 sweet_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sweet_crickets',
'endframe': 2746425,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (23) jun grain0 takunia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takunia',
'endframe': 187145,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (24) jun grain0 weddell
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 26035430,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (25) jun grain0 weddellpock
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddellpock',
'endframe': 640128,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (26) jun grain0 wind_moderate
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_moderate',
'endframe': 2147840,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (27) jun grain0 wind_strong
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_strong',
'endframe': 3889920,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (28) jun grain0 yang_bird
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yang_bird',
'endframe': 5445632,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (29) jun grain0 yangdrums
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yangdrums',
'endframe': 10656768,
'playfunc': 'grain0',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */