/*presets for jun saved at 230825_002305*/

//: (0) jun infplay bird_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'bird_crickets',
'endframe': 2451380,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) jun infplay birdcarman
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarman',
'endframe': 6750651,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) jun infplay birdcarmanshort
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarmanshort',
'endframe': 3105211,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) jun infplay columbia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'columbia',
'endframe': 107520,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) jun infplay cricket_ff
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_ff',
'endframe': 979297,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (5) jun infplay cricket_taps
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_taps',
'endframe': 544543,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (6) jun infplay crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crickets',
'endframe': 1862334,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (7) jun infplay crossing
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crossing',
'endframe': 1406259,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (8) jun infplay default
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'default',
'endframe': 188893,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (9) jun infplay echo_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'echo_crickets',
'endframe': 2746425,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (10) jun infplay fones
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'fones',
'endframe': 135274,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (11) jun infplay hanbaiki
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'hanbaiki',
'endframe': 398624,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (12) jun infplay kiiroi
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'kiiroi',
'endframe': 473791,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (13) jun infplay lake_plane
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'lake_plane',
'endframe': 1067182,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (14) jun infplay loud_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'loud_crickets',
'endframe': 2121727,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (15) jun infplay melodia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodia',
'endframe': 705600,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (16) jun infplay melodic_road
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodic_road',
'endframe': 1167623,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (17) jun infplay noisebirdsclick
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 1798102,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (18) jun infplay pilgrims
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'pilgrims',
'endframe': 2580480,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (19) jun infplay rough_steps
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'rough_steps',
'endframe': 772138,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (20) jun infplay silence
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'silence',
'endframe': 441000,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (21) jun infplay swallows
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'swallows',
'endframe': 27691528,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (22) jun infplay sweet_crickets
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sweet_crickets',
'endframe': 2746425,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (23) jun infplay takunia
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takunia',
'endframe': 187145,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (24) jun infplay weddell
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 26035430,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (25) jun infplay weddellpock
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddellpock',
'endframe': 640128,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (26) jun infplay wind_moderate
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_moderate',
'endframe': 2147840,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (27) jun infplay wind_strong
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_strong',
'endframe': 3889920,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (28) jun infplay yang_bird
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yang_bird',
'endframe': 5445632,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (29) jun infplay yangdrums
(
'amp': [ 1.0, "Xyz(5, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yangdrums',
'endframe': 10656768,
'playfunc': 'infplay',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */