/*presets for asayo saved at 230819_000120*/

//: (0) asayo plainsynthtest wind_strong
(
'amp': [ 0.17693373645755, "", 'off' ],
'buf': 'wind_strong',
'dur': [ 1, "", 'off' ],
'endframe': 1150514,
'freq': [ 365.53987380384, "", 'off' ],
'playfunc': 'plainsynthtest',
'pos': [ 0.10958904109589, "", 'off' ],
'rate': [ 0.213190144172, "", 'off' ],
'startframe': 888712,
'trate': [ 0.5296803652968, "", 'off' ],
'vol': [ 1.0510623214695, "", 'off' ],
)
//: (1) asayo grainecho wind_strong
(
'amp': [ 0.37832262534643, "", 'off' ],
'buf': 'wind_strong',
'dur': [ 0.6468253968254, "", 'off' ],
'endframe': 1150514,
'playfunc': 'grainecho',
'pos': [ 0.31746031746032, "", 'off' ],
'rate': [ 0.22758459260748, "", 'off' ],
'startframe': 888712,
'trate': [ 0.79365079365079, "", 'off' ],
'vol': [ 6.6176933736458, "", 'off' ],
)
//: (2) asayo grainecho2 wind_strong
(
'amp': [ 0, "", 'off' ],
'buf': 'wind_strong',
'dur': [ 0, "", 'off' ],
'endframe': 1150514,
'playfunc': 'grainecho2',
'pos': [ 0, "", 'off' ],
'rate': [ 0, "", 'off' ],
'startframe': 888712,
'trate': [ 0, "", 'off' ],
'vol': [ 0, "", 'off' ],
)
/* THE END */