/*presets for yoshimitsuL saved at 231019_105921*/

//: (0) yoshimitsuL grainfrothl weddell
//scene 1 
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'weddell',
'endframe': 2451380,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) yoshimitsuL grainfrothl yang_bird
//scene 2 
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'yang_bird',
'endframe': 6750651,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) yoshimitsuL grainfrothl yang_bird
//scene 3 
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'yang_bird',
'endframe': 3105211,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) yoshimitsuL grainfrothl weddell
//scene 4 
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 107520,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) yoshimitsuL grainfrothl weddell
//scene 4 
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 979297,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */