/*presets for yoshimitsuR saved at 231019_105924*/

//: (0) yoshimitsuR grainfrothl columbia
//scene 1 
(
'amp': [ 1.0, "Xyz(2, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'columbia',
'endframe': 2451380,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x2.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z2.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) yoshimitsuR grainfrothl wind_moderate
//scene 2 
(
'amp': [ 1.0, "Xyz(2, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'wind_moderate',
'endframe': 6750651,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x2.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z2.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) yoshimitsuR grainfrothl yangdrums
//scene 3 
(
'amp': [ 1.0, "Xyz(2, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'yangdrums',
'endframe': 3105211,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x2.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z2.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) yoshimitsuR grainfrothl yang_bird
//scene 4 
(
'amp': [ 1.0, "Xyz(2, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yang_bird',
'endframe': 107520,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x2.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z2.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) yoshimitsuR grainfrothl weddell
(
'amp': [ 1.0, "Xyz(2, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 979297,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x2.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z2.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */