/*presets for mary2 saved at 231021_065129*/

//: (0) mary2 grainfrothl fones
// scene 1 rh  
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'fones',
'endframe': 2451380,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) mary2 grainfrothl noisebirdsclick
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 6750651,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x7.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z7.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) mary2 grainfrothl fones
//scene 3  
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'fones',
'endframe': 3105211,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x7.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z7.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) mary2 grainfrothl noisebirdsclick
//scene 4  
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 107520,
'playfunc': 'grainfrothl',
'pos': [ 0.079365079365079, "\\x7.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z7.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */