/*presets for mary1 saved at 231020_191131*/

//: (0) mary1 grainfroth fones
// scene 1 rh 
(
'amp': [ 1.0, "Xyz(6, 0.2, 0.1, 1.5) * 0.5", 'on' ],
'buf': 'fones',
'endframe': 2451380,
'playfunc': 'grainfroth',
'pos': [ 0.079365079365079, "\\x5.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z5.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) mary1 grainfroth noisebirdsclick
(
'amp': [ 1.0, "Xyz(7, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 6750651,
'playfunc': 'grainfroth',
'pos': [ 0.079365079365079, "\\x7.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z7.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) mary1 grainfroth fones
//scene 3 
(
'amp': [ 1.0, "Xyz(7, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'fones',
'endframe': 3105211,
'playfunc': 'grainfroth',
'pos': [ 0.079365079365079, "\\x7.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z7.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) mary1 grainfroth noisebirdsclick
//scene 4 
(
'amp': [ 1.0, "Xyz(7, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 107520,
'playfunc': 'grainfroth',
'pos': [ 0.079365079365079, "\\x7.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z7.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */