/*presets for jun saved at 230825_002305*/

//: (0) jun grainecho2 bird_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'bird_crickets',
'endframe': 2451380,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) jun grainecho2 birdcarman
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarman',
'endframe': 6750651,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) jun grainecho2 birdcarmanshort
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarmanshort',
'endframe': 3105211,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) jun grainecho2 columbia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'columbia',
'endframe': 107520,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) jun grainecho2 cricket_ff
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_ff',
'endframe': 979297,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (5) jun grainecho2 cricket_taps
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_taps',
'endframe': 544543,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (6) jun grainecho2 crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crickets',
'endframe': 1862334,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (7) jun grainecho2 crossing
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crossing',
'endframe': 1406259,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (8) jun grainecho2 default
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'default',
'endframe': 188893,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (9) jun grainecho2 echo_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'echo_crickets',
'endframe': 2746425,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (10) jun grainecho2 fones
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'fones',
'endframe': 135274,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (11) jun grainecho2 hanbaiki
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'hanbaiki',
'endframe': 398624,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (12) jun grainecho2 kiiroi
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'kiiroi',
'endframe': 473791,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (13) jun grainecho2 lake_plane
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'lake_plane',
'endframe': 1067182,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (14) jun grainecho2 loud_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'loud_crickets',
'endframe': 2121727,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (15) jun grainecho2 melodia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodia',
'endframe': 705600,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (16) jun grainecho2 melodic_road
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodic_road',
'endframe': 1167623,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (17) jun grainecho2 noisebirdsclick
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 1798102,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (18) jun grainecho2 pilgrims
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'pilgrims',
'endframe': 2580480,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (19) jun grainecho2 rough_steps
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'rough_steps',
'endframe': 772138,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (20) jun grainecho2 silence
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'silence',
'endframe': 441000,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (21) jun grainecho2 swallows
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'swallows',
'endframe': 27691528,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (22) jun grainecho2 sweet_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sweet_crickets',
'endframe': 2746425,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (23) jun grainecho2 takunia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takunia',
'endframe': 187145,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (24) jun grainecho2 weddell
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 26035430,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (25) jun grainecho2 weddellpock
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddellpock',
'endframe': 640128,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (26) jun grainecho2 wind_moderate
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_moderate',
'endframe': 2147840,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (27) jun grainecho2 wind_strong
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_strong',
'endframe': 3889920,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (28) jun grainecho2 yang_bird
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yang_bird',
'endframe': 5445632,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (29) jun grainecho2 yangdrums
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yangdrums',
'endframe': 10656768,
'playfunc': 'grainecho2',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */