/*presets for jun saved at 230825_002305*/

//: (0) jun magshift bird_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'bird_crickets',
'endframe': 2451380,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (1) jun magshift birdcarman
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarman',
'endframe': 6750651,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (2) jun magshift birdcarmanshort
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'birdcarmanshort',
'endframe': 3105211,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (3) jun magshift columbia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'columbia',
'endframe': 107520,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (4) jun magshift cricket_ff
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_ff',
'endframe': 979297,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (5) jun magshift cricket_taps
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'cricket_taps',
'endframe': 544543,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (6) jun magshift crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crickets',
'endframe': 1862334,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (7) jun magshift crossing
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'crossing',
'endframe': 1406259,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (8) jun magshift default
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'default',
'endframe': 188893,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (9) jun magshift echo_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'echo_crickets',
'endframe': 2746425,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (10) jun magshift fones
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'fones',
'endframe': 135274,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (11) jun magshift hanbaiki
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'hanbaiki',
'endframe': 398624,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (12) jun magshift kiiroi
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'kiiroi',
'endframe': 473791,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (13) jun magshift lake_plane
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'lake_plane',
'endframe': 1067182,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (14) jun magshift loud_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'loud_crickets',
'endframe': 2121727,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (15) jun magshift melodia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodia',
'endframe': 705600,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (16) jun magshift melodic_road
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'melodic_road',
'endframe': 1167623,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (17) jun magshift noisebirdsclick
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'noisebirdsclick',
'endframe': 1798102,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (18) jun magshift pilgrims
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'pilgrims',
'endframe': 2580480,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (19) jun magshift rough_steps
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'rough_steps',
'endframe': 772138,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (20) jun magshift silence
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'silence',
'endframe': 441000,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (21) jun magshift swallows
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'swallows',
'endframe': 27691528,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (22) jun magshift sweet_crickets
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'sweet_crickets',
'endframe': 2746425,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (23) jun magshift takunia
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'takunia',
'endframe': 187145,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (24) jun magshift weddell
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddell',
'endframe': 26035430,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (25) jun magshift weddellpock
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'weddellpock',
'endframe': 640128,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (26) jun magshift wind_moderate
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_moderate',
'endframe': 2147840,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (27) jun magshift wind_strong
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'wind_strong',
'endframe': 3889920,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (28) jun magshift yang_bird
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yang_bird',
'endframe': 5445632,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
//: (29) jun magshift yangdrums
(
'amp': [ 1.0, "Xyz(1, 0.2, 0.1, 1.5)", 'on' ],
'buf': 'yangdrums',
'endframe': 10656768,
'playfunc': 'magshift',
'pos': [ 0.079365079365079, "\\x1.sr", 'on' ],
'startframe': 0,
'trate': [ 0.48412698412698, "\\z1.sr", 'on' ],
'vol': [ 3.356638951877, "", 'off' ],
)
/* THE END */